import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen bg-[#0D1B2A] text-white">
        
      
        <aside className="w-72 bg-[#1B263B] p-4">
          <h2 className="text-xl font-bold mb-4">OSINT Dashboard</h2>
          <nav className="space-y-2">
            <Link href="/" className="block py-2 hover:text-blue-400">Countries</Link>
            <Link href="/news" className="block py-2 hover:text-blue-400">All News</Link>
          </nav>
        </aside>

   
        <main className="flex-1 p-6 overflow-y-auto">
          {children}
        </main>

      </body>
    </html>
  );
}